import type { KiprisSearchResult } from '../types';

const KIPRIS_API_KEY = 'VFgld/jv0xM4MPyjPFpXjMpN0YGfPEIllx4dNNRj4cY=';
const KIPRIS_API_BASE_URL = 'http://plus.kipris.or.kr/openapi/rest';

// This map helps route the API call to the correct KIPRIS service endpoint.
const apiServiceMap: { [key: string]: string } = {
  getAdvancedSearch: 'patUtiInfoSearchService/getAdvancedSearch',
  // This can be expanded if Gemini is prompted to generate strategies for other patent types.
};

/**
 * Parses the custom query string generated by Gemini into URLSearchParams.
 * Example: "ipcNumber=G06K9/62* AND inventionTitle=(이미지 AND 인식)"
 * becomes URLSearchParams with 'ipcNumber' and 'inventionTitle' keys.
 * @param query The query string from the ApiStrategy.
 * @returns A URLSearchParams object.
 */
export const parseKiprisQuery = (query: string): URLSearchParams => {
  const params = new URLSearchParams();
  // The Gemini prompt uses ' AND ' as a separator for different search criteria.
  // This regex splits by ' AND ' only if it is followed by what looks like a new parameter key (e.g., word=).
  const criteria = query.split(/ AND (?=[a-zA-Z]+=)/);
  criteria.forEach(criterion => {
    const parts = criterion.split('=');
    if (parts.length >= 2) {
      const key = parts[0].trim();
      const value = parts.slice(1).join('=').trim();
      if (key && value) {
        params.append(key, value);
      }
    }
  });
  return params;
};

const getFirstElement = (node: Document | Element, tagName: string): Element | null => {
  const elements = node.getElementsByTagName(tagName);
  return elements.length > 0 ? (elements.item(0) as Element) : null;
};

const getElementText = (node: Document | Element, tagName: string): string => {
  const element = getFirstElement(node, tagName);
  return element?.textContent?.trim() ?? '';
};

// Function to fetch data from KIPRIS API
export const fetchKiprisData = async (api: string, query: string): Promise<KiprisSearchResult[]> => {
  const servicePath = apiServiceMap[api];
  if (!servicePath) {
    throw new Error(`Unsupported KIPRIS API operation: ${api}`);
  }

  const queryParams = parseKiprisQuery(query);
  queryParams.append('accessKey', KIPRIS_API_KEY);

  if (!queryParams.has('numOfRows')) {
    queryParams.append('numOfRows', '10');
  }

  const url = `${KIPRIS_API_BASE_URL}/${servicePath}?${queryParams.toString()}`;

  try {
    // KIPRIS API does not support HTTPS and has CORS issues. A proxy is required for client-side fetching.
    // We will use a simple public proxy for this demonstration.
    const proxyUrl = `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;
    const response = await fetch(proxyUrl);

    const xmlString = await response.text();
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlString, 'application/xml');

    const errorElement = getFirstElement(xmlDoc, 'error');
    if (errorElement) {
      const errorCode = getElementText(errorElement, 'errorCode');
      const errorMessage = getElementText(errorElement, 'errorMessage');
      throw new Error(`KIPRIS API Error: [${errorCode}] ${errorMessage}`);
    }

    if (!response.ok) {
      throw new Error(`KIPRIS API request failed with status ${response.status}. The proxy might be down or there could be an issue with the API server.`);
    }

    const results: KiprisSearchResult[] = Array.from(xmlDoc.getElementsByTagName('item'))
      .map(item => ({
        company: getElementText(item, 'applicantName'),
        patentTitle: getElementText(item, 'inventionTitle'),
        applicationNumber: getElementText(item, 'applicationNumber'),
        date: getElementText(item, 'applicationDate'),
      }))
      .filter(result => result.patentTitle && result.applicationNumber);

    return results;
  } catch (error) {
    console.error('Error fetching or parsing KIPRIS data:', error);
    if (error instanceof Error) {
      if (error.message.includes('Failed to fetch')) {
        throw new Error('네트워크 오류가 발생했습니다. API 서버에 연결할 수 없습니다. CORS 정책 또는 네트워크 연결을 확인해주세요.');
      }
      throw new Error(`KIPRIS API 호출 중 오류가 발생했습니다: ${error.message}`);
    }
    throw new Error('KIPRIS API를 호출하는 동안 알 수 없는 오류가 발생했습니다.');
  }
};
